extends: ["eslint:recommended"]
env:
  es6: true
  node: true
parser: "babel-eslint"
parserOptions:
  sourceType: "module"
plugins: [
  "babel"
]
rules:
  #
  # Possible errors
  #
  "comma-dangle": [1, "always-multiline"]
  #
  # Best practices
  #
  "array-callback-return": 2
  "block-scoped-var": 2
  "complexity": [2, 10]
  "consistent-return": 2
  "curly": [2, "multi-line"]
  "default-case": 2
  "dot-location": [2, "property"]
  "dot-notation": 1
  "eqeqeq": [2, "smart"]
  "no-alert": 2
  "no-caller": 2
  "no-case-declarations": 2
  "no-else-return": 1
  "no-empty-pattern": 2
  "no-eq-null": 2
  "no-eval": 2
  "no-extend-native": 2
  "no-extra-bind": 2
  "no-floating-decimal": 1
  "no-implicit-coercion": 1
  "no-implicit-globals": 2
  "no-implied-eval": 2
  "no-labels": 2
  "no-lone-blocks": 1
  "no-loop-func": 2
  "no-magic-numbers": 1
  "no-multi-spaces": 1
  "no-native-reassign": 2
  "no-new-func": 2
  "no-new-wrappers": 2
  "no-new": 2
  "no-octal-escape": 2
  "no-param-reassign": 2
  "no-proto": 2
  "no-return-assign": 2
  "no-script-url": 2
  "no-self-compare": 2
  "no-sequences": 2
  "no-throw-literal": 2
  "no-unmodified-loop-condition": 2
  "no-unused-expressions": 2
  "no-useless-call": 2
  "no-useless-concat": 2
  "no-void": 2
  "no-warning-comments": [2, { terms: ["todo", "fixme"], location: "anywhere"}]
  "no-with": 2
  "radix": 2
  "wrap-iife": 2
  "yoda": 2
  #
  # Variables
  #
  "init-declarations": 2
  "no-shadow-restricted-names": 2
  "no-shadow": 2
  "no-undef-init": 2
  "no-use-before-define": [2, "nofunc"]
  #
  # Node.js and CommonJS
  #
  "global-require": 2
  "handle-callback-err": 2
  "no-mixed-requires": [2, {"grouping": true}]
  "no-new-require": 2
  "no-path-concat": 2
  "no-process-exit": 2
  #
  # Stylistic Issues
  #
  "array-bracket-spacing": 0
  "block-spacing": [1, "always"]
  "brace-style": [1, "1tbs", { "allowSingleLine": true }]
  "camelcase": 1
  "comma-spacing": [1, {"before": false, "after": true}]
  "comma-style": [1, "last"]
  "computed-property-spacing": [1, "never"]
  "consistent-this": [1, "self"]
  "eol-last": 1
  "func-names": 1
  "func-style": [1, "declaration", { "allowArrowFunctions": true }]
  "id-length": [1, {"min": 2, "exceptions": ["i"]}]
  "indent": [2, "tab"]
  "key-spacing": 1
  "keyword-spacing": 1
  "linebreak-style": 1
  "lines-around-comment":
    - 1
    -
      "beforeBlockComment": true
      "beforeLineComment": true
      "allowBlockStart": true
      "allowObjectStart": true
      "allowArrayStart": true
  "max-depth": [2, 3]
  "max-len": [1, 100, {"ignoreUrls": true, "ignoreComments": true}]
  "max-nested-callbacks": [2, 3]
  "max-params": [2, 3]
  "new-parens": 1
  "no-array-constructor": 2
  "no-bitwise": 2
  "no-continue": 2
  "no-lonely-if": 2
  "no-mixed-spaces-and-tabs": [1, "smart-tabs"]
  "no-multiple-empty-lines": [2, {"max": 1}]
  "no-negated-condition": 2
  "no-nested-ternary": 2
  "no-plusplus": 2
  "no-whitespace-before-property": 1
  "no-spaced-func": 1
  "no-trailing-spaces": [1, { "skipBlankLines": true }]
  "no-underscore-dangle": 2
  "no-unneeded-ternary": 2
  "object-curly-spacing": 0
  "one-var": [2, "never"]
  "operator-assignment": [2, "always"]
  "padded-blocks": 0
  "quote-props": [1, "consistent-as-needed"]
  "quotes": [1, "single"]
  "semi-spacing": 1
  "semi": 2
  "space-before-blocks": 1
  "space-before-function-paren": [1, "never"]
  "space-in-parens": [1, "never"]
  "space-infix-ops": 1
  "space-unary-ops": [1, { "words": true, "nonwords": false }]
  "spaced-comment": 1
  "wrap-regex": 2
  #
  # ECMAScript 6
  #
  "arrow-body-style": [1, "as-needed"]
  "arrow-parens": 0
  "arrow-spacing": 1
  "constructor-super": 2
  "generator-star-spacing": 0
  "no-class-assign": 2
  "no-confusing-arrow": 2
  "no-const-assign": 2
  "no-dupe-class-members": 2
  "no-this-before-super": 2
  "no-var": 2
  "no-useless-constructor": 2
  "object-shorthand": 0
  "prefer-arrow-callback": 2
  "prefer-const": 2
  "prefer-reflect": 2
  "prefer-rest-params": 2
  "prefer-spread": 2
  "prefer-template": 1
  "require-yield": 2
  "yield-star-spacing": [1, "before"]
  #
  # eslint-plugin-babel
  #
  "babel/generator-star-spacing": [1, "before"]
  "babel/array-bracket-spacing": 1
  "babel/object-curly-spacing":
    - 2
    - "always"
    -
      objectsInObjects: false
      arraysInObjects: false
  "babel/object-shorthand": [2, "always"]
  "babel/arrow-parens": [1, "always"]
  "babel/no-await-in-loop": 1
