extends:
  eslint-config-airbnb-base

parser:
  babel-eslint

settings:
  import/extensions:
    - .js
    - .mjs

plugins:
  - babel

parserOptions:
  sourceType: module
  ecmaVersion: 6

env:
  es6: true

rules:
  indent: [error, tab]
  no-unused-vars: warn
  semi: [error, never]
  new-cap: off
  quotes: [warn, single, {
    avoidEscape: true, allowTemplateLiterals: true
  }]
  no-use-before-define: [error, nofunc]
  no-tabs: off

  #
  # eslint-plugin-babel
  #
  generator-star-spacing: off
  babel/generator-star-spacing: [warn, before]

  array-bracket-spacing: off
  babel/array-bracket-spacing: warn

  object-curly-spacing: off
  babel/object-curly-spacing: [error, always, {
    objectsInObjects: false, arraysInObjects: true
  }]

  object-shorthand: off
  babel/object-shorthand: [error, always]

  arrow-parens: off
  babel/arrow-parens: [warn, always]

  babel/no-await-in-loop: warn

  import/extensions: [error, always, {
    js: never,
    mjs: never
  }]
